image: docker:stable
services:
  - docker:dind
before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-docker:
  stage: build
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  - docker push registry.gitlab.com/metuzalem/to_do:latest
  