image: docker:stable
services:
  - docker:dind
before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY

build-docker:
  stage: build
  script:
  - docker build --pull -t minha-imagens .
  - docker tag minha-imagens metuzalem/minha-imagens:latest
  - docker push metuzalem/minha-imagens:latest