image: docker:stable
services:
  - docker:dind
before_script:
  - docker info
  -  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  #- docker login registry.example.com -u metuzalem -p $CI_BUILD_TOKEN
  #- echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build-docker:
  stage: build
  script:
  - docker build -t minha-imagens .
  - docker tag minha-imagens metuzalem/minha-imagens
  - docker push metuzalem/minha-imagens:latest

  
  # glpat-BHay6iHUdCaKzZK1CVuw