image: docker:stable
services:
  - docker:dind
before_script:
  - docker info
  - echo ${{ CI_REGISTRY_TOKEN }} | docker login --username ${{ CI_REGISTRY_USER }} --password-stdin
  
build-docker:
  stage: build


  script:
  - docker build .
