image: docker:stable
services:
  - docker:dind
before_script:
  - docker info
  - cat "CI_REGISTRY_TOKEN" | docker login -u "CI_REGISTRY_USER" --password-stdin registry.gitlab.com
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-docker:
  stage: build

  script:
  - docker build -t minha-imagem .
  - docker tag minha-imagem metuzalem/to_do:latest
  - docker push metuzalem/to_do:latest